services:
  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "8000:9000"  # PHP-FPM (ما بعداً nginx یا artisan serve اضافه می‌کنیم اگر نیاز)
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=task_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - backend-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "3000:80"  # Nginx on 80
    volumes:
      - ./frontend:/app
    networks:
      - frontend-net
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: task-db
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: task-redis
    networks:
      - backend-net
    restart: unless-stopped

volumes:
  db-data:

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge
